version: '3'

networks:
    basic:

services:
    keycloak.example.com:
        image: jboss/keycloak
        container_name: keycloak.example.com
        environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - DB_VENDOR=h2
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_PASSWORD=password
        ports:
        - "8080:8080"
        volumes:
          - ./example-theme:/opt/jboss/keycloak/themes/example-theme
        networks:
            - basic
